dataset_dir = '/aux/sbroniko/vader-rover/logs/MSEE1-dataset/generation-testing/';
data_output_dirname = 'detections-test20150618';

[sim_dsift_chisq_05, sim_dsift_emd_05, sim_chist_chisq_05, sim_chist_emd_05] = ...
    step_4_build_similarity_matrix(dataset_dir,data_output_dirname,0.05);

[sim_dsift_chisq_10, sim_dsift_emd_10, sim_chist_chisq_10, sim_chist_emd_10] = ...
    step_4_build_similarity_matrix(dataset_dir,data_output_dirname,0.10);

[sim_dsift_chisq_15, sim_dsift_emd_15, sim_chist_chisq_15, sim_chist_emd_15] = ...
    step_4_build_similarity_matrix(dataset_dir,data_output_dirname,0.15);

[sim_dsift_chisq_20, sim_dsift_emd_20, sim_chist_chisq_20, sim_chist_emd_20] = ...
    step_4_build_similarity_matrix(dataset_dir,data_output_dirname,0.2);

save('asm_20150728c.mat','sim_dsift_chisq_05','sim_dsift_emd_05',...
    'sim_chist_chisq_05','sim_chist_emd_05','sim_dsift_chisq_10',...
    'sim_dsift_emd_10','sim_chist_chisq_10','sim_chist_emd_10',...
    'sim_dsift_chisq_15','sim_dsift_emd_15','sim_chist_chisq_15',...
    'sim_chist_emd_15','sim_dsift_chisq_20','sim_dsift_emd_20',...
    'sim_chist_chisq_20','sim_chist_emd_20');

fprintf('test_step_4 complete\n');