function compute_and_save_asm_iros2016(dataset_dir,data_output_dirname)
% dataset_dir = '/aux/sbroniko/vader-rover/logs/MSEE1-dataset/ralicra2016/';
% data_output_dirname = ['detections-test-20160223-',dir_suffix,'-',typenum];
filename = [dataset_dir,'asm_',data_output_dirname,'.mat'];
[sim_dsift_chisq, sim_dsift_emd, sim_chist_chisq_3d, sim_chist_emd_3d, sim_chist_chisq_2d, sim_chist_emd_2d] = ...
    step_4_build_similarity_matrix(dataset_dir,data_output_dirname,0.50);

save(filename,...
    'sim_dsift_chisq','sim_dsift_emd',...
    'sim_chist_chisq_3d','sim_chist_emd_3d',...
    'sim_chist_chisq_2d','sim_chist_emd_2d');

fprintf('compute_and_save_asm complete\n');